import {
  stockFull,
  stockOos,
  type SeedProduct,
} from "./types";

// ---------------------------------------------------------------------------
// CLASSICS — 50 core GR models (€89–169, fuller stock)
// Brand mix: Nike 14 · Adidas 10 · NB 9 · ASICS 7 · Puma 6 · Converse 4
// ---------------------------------------------------------------------------

export const CLASSICS: SeedProduct[] = [
	// --- Nike (14) ----------------------------------------------------------
	{
		slug: 'nike-air-force-1-low',
		name: "Air Force 1 '07 Low",
		description:
			'An icon of clean. Full-grain leather, crisp stitching, and the pivot-point outsole that defined a generation.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'new',
		variants: [
			{
				color: 'Triple White',
				colorHex: '#FFFFFF',
				colorFamily: 'white',
				description:
					'All-white leather AF1. Crisp stitching and the classic pivot-point outsole in its cleanest form.',
				price: 119,
				image: 8,
				cloudinaryId: 'nike-air-force-1-low-triple-white_abkdpp',
				stock: stockFull(10),
			},
			{
				color: 'Triple Black',
				colorHex: '#111111',
				colorFamily: 'black',
				description:
					'All-black AF1 with tonal Swoosh. Premium leather and the pivot-point outsole in stealth mode.',
				price: 119,
				image: 2,
				cloudinaryId: 'nike-air-force-1-low-black_g7uu0o',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'nike-dunk-low-panda',
		name: "Dunk Low 'Panda'",
		description:
			'A wardrobe essential. Crisp white leather with black overlays for a clean look that goes with everything.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'new',
		variants: [
			{
				color: 'Black / White',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 119,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda-black-and-white_mwdwie',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'nike-dunk-low-grey-fog',
		name: "Dunk Low 'Grey Fog'",
		description:
			'Muted grey tones on premium leather. A subtle everyday Dunk that pairs with anything in your rotation.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Grey Fog',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 119,
				image: 9,
				cloudinaryId: 'nike-dunk-low-grey-fog_cmr5kd',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'nike-air-max-90',
		name: 'Air Max 90',
		description:
			'The Nike Air Max 90 stays true to its OG roots with the iconic Waffle sole, stitched overlays, and classic TPU accents.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'discount',
		discountValue: 20,
		variants: [
			{
				color: 'Triple White',
				colorHex: '#F5F5F5',
				colorFamily: 'white',
				price: 139,
				image: 7,
				cloudinaryId: 'nike-air-max-90-triple-white_asscyq',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'nike-air-max-1-86-og-white-university-red',
		name: "Air Max 1 '86 OG White University Red'",
		description:
			'The original visible Air unit. Timeless suede-and-mesh construction with the unmistakable Air Max silhouette.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'White / Red',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 149,
				image: 0,
				cloudinaryId: 'nike-air-max-1-86-og-white-university-red_eruyp2',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'nike-air-max-97',
		name: 'Air Max 97',
		description:
			'Inspired by Japanese bullet trains. Full-length visible Air and a rippling metallic upper for futuristic flow.',
		brand: 'Nike',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Silver Bullet',
				colorHex: '#B8BCC2',
				colorFamily: 'silver',
				price: 169,
				image: 11,
				cloudinaryId: 'nike-air-max-97-silver-bullet_myodkd',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'nike-p-6000',
		name: 'P-6000',
		description:
			'Y2K running energy. A metallic, layered upper on a chunky retro runner sole for full early-2000s flavour.',
		brand: 'Nike',
		category: 'running',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Metallic Silver',
				colorHex: '#B8BCC2',
				colorFamily: 'silver',
				price: 139,
				image: 11,
				cloudinaryId: 'nike-p-6000-metallic-silver_rslyom',
				stock: stockFull(7),
			},
			{
				color: 'Volt',
				colorHex: '#CCFF00',
				colorFamily: 'yellow',
				description:
					'Y2K P-6000 punched up with volt overlays. Layered runner energy that refuses to whisper.',
				price: 139,
				image: 15,
				cloudinaryId: 'nike-p-6000-volt_rz59yy',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'nike-vomero-5',
		name: 'Vomero 5',
		description:
			'Early-2000s runner reborn. Layered mesh and synthetic panels with plush Zoom Air cushioning for all-day comfort.',
		brand: 'Nike',
		category: 'running',
		gender: 'unisex',
		badge: 'new',
		variants: [
			{
				color: 'Photon Dust',
				colorHex: '#B8BCC2',
				colorFamily: 'silver',
				price: 159,
				image: 10,
				cloudinaryId: 'nike-vomero-5-photon-dust_ejmoto',
				stock: stockFull(8),
			},
			{
				color: 'Volt Yellow',
				colorHex: '#D4FF00',
				colorFamily: 'yellow',
				description:
					'Vomero 5 with volt-yellow hits on layered mesh. Plush Zoom Air with neon attitude.',
				price: 159,
				image: 16,
				cloudinaryId: 'nike-vomero-5-volt-yellow_u7dfur',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'nike-cortez',
		name: 'Cortez',
		description:
			'The original road runner. Lightweight nylon and suede with a classic foam midsole — West Coast heritage in every step.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Forrest Gump',
				colorHex: '#6366F1',
				colorFamily: 'multi',
				price: 99,
				image: 5,
				cloudinaryId: 'nike-cortez-forrest-gump_tb1fnv',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'nike-blazer-mid-77',
		name: "Blazer Mid '77",
		description:
			'Vintage hoops style. A simple suede-and-leather upper with an oversized Swoosh and a vulcanised midsole.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'discount',
		discountValue: 15,
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 109,
				image: 8,
				cloudinaryId: 'nike-blazer-mid-77-split-white-black_cb3aew',
				stock: stockFull(8),
			},
			{
				color: 'Electric Green',
				colorHex: '#39FF14',
				colorFamily: 'green',
				description:
					'Blazer Mid lit up in electric green suede. Oversized Swoosh and vulcanised midsole — impossible to miss.',
				price: 119,
				image: 17,
				cloudinaryId: 'nike-blazer-mid-77-electric-green_l9jfhc',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'air-jordan-1-mid',
		name: 'Air Jordan 1 Mid',
		description:
			'Jordan heritage at a mid-cut height. Premium materials and classic colour blocking for everyday court style.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: 'new',
		variants: [
			{
				color: 'White',
				colorHex: '#FFFFFF',
				colorFamily: 'white',
				price: 139,
				image: 4,
				cloudinaryId: 'air-jordan-1-mid-white-black_im0vtt',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'air-jordan-3-retro',
		name: 'Air Jordan 3 Retro',
		description:
			"Tinker Hatfield's masterpiece. Elephant print, visible Air, and a silhouette that changed basketball footwear forever.",
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'White Cement',
				colorHex: '#F5F5F5',
				colorFamily: 'white',
				price: 169,
				image: 6,
				cloudinaryId: 'air-jordan-3-retro-white-cement_yynjoa',
				stock: stockFull(5),
			},
		],
	},
	{
		slug: 'nike-react-vision',
		name: 'React Vision',
		description:
			'Futuristic runner vibes. React foam and layered textures create a bold, comfortable silhouette for city miles.',
		brand: 'Nike',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Photon Dust',
				colorHex: '#D1D5DB',
				colorFamily: 'grey',
				price: 129,
				image: 12,
				cloudinaryId: 'nike-react-vision-photon-dust_bujb6t',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'nike-killshot-2',
		name: 'Killshot 2',
		description:
			'Retro tennis style with a gum sole. Soft leather upper and a low profile that works from court to coffee run.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'discount',
		discountValue: 10,
		variants: [
			{
				color: 'Black',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 99,
				image: 3,
				cloudinaryId: 'nike-killshot-2-black-white_cpmw1p',
				stock: stockFull(9),
			},
		],
	},

	// --- Adidas (10) --------------------------------------------------------
	{
		slug: 'adidas-samba-og',
		name: 'Samba OG',
		description:
			'A terrace classic reborn. Soft leather, suede T-toe, gum sole, and gold foil branding — timeless from pitch to pavement.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'Cloud White',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				description:
					'Cloud White Samba with suede T-toe and gum sole. Gold foil branding on a terrace classic.',
				price: 110,
				image: 3,
				cloudinaryId: 'adidas-samba-og-cloude-white_bfavzk',
				stock: stockFull(10),
			},
			{
				color: 'Core Black',
				colorHex: '#111111',
				colorFamily: 'black',
				description:
					'Core Black Samba with suede T-toe and gum sole. A darker take on the terrace icon.',
				price: 110,
				image: 4,
				cloudinaryId: 'adidas-samba-og-core-black_z4zuds',
				stock: stockFull(8),
			},
			{
				color: 'Lucid Pink',
				colorHex: '#FF4DA6',
				colorFamily: 'pink',
				description:
					'Samba OG in lucid pink suede. Gum sole and gold foil branding with loud terrace energy.',
				price: 110,
				image: 18,
				cloudinaryId: 'adidas-samba-og-lucid-pink_dxwegg',
				stock: stockFull(7),
			},
			{
				color: 'Bold Orange',
				colorHex: '#FF6A00',
				colorFamily: 'orange',
				description:
					'High-vis orange Samba OG. Soft suede, T-toe overlay, and gum sole built to stand out.',
				price: 110,
				image: 15,
				cloudinaryId: 'adidas-samba-og-bold-orange_dwaw7k',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'adidas-handball-spezial',
		name: 'Handball Spezial',
		description:
			'Indoor heritage meets street style. Soft suede upper with a gum sole and classic three stripes in bold colour.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'new',
		variants: [
			{
				color: 'Collegiate Navy',
				colorHex: '#1E3A5F',
				colorFamily: 'navy',
				price: 110,
				image: 1,
				cloudinaryId: 'adidas-handball-spezial-navy_vwmkrh',
				stock: stockFull(9),
			},
			{
				color: 'Navy Gum',
				colorHex: '#1B2A4A',
				colorFamily: 'navy',
				description:
					'Deep navy Spezial with a rich gum sole. Soft suede and classic stripes for everyday heat.',
				price: 110,
				image: 1,
				cloudinaryId: 'adidas-handball-spezial-navy-gum_omguzw',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'adidas-gazelle-indoor',
		name: 'Gazelle Indoor',
		description: 'Retro indoor style with a plush suede upper, contrast three stripes, and a low, grippy gum outsole.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: null,
		variants: [
			{
				color: 'Blue Bird',
				colorHex: '#3B6FB5',
				colorFamily: 'blue',
				price: 120,
				image: 1,
				cloudinaryId: 'adidas-gazelle-indoor-blue_decm24',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'adidas-campus-00s',
		name: 'Campus 00s',
		description:
			'Bold, chunky, and unmistakably 2000s. Premium suede with oversized branding and a comfortable footbed.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: 'discount',
		discountValue: 15,
		variants: [
			{
				color: 'Triple Black',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 115,
				image: 4,
				cloudinaryId: 'adidas-campus-00s-triple-black_qe6jwf',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'adidas-superstar',
		name: 'Superstar',
		description:
			'The shell toe legend. Smooth leather upper with the iconic rubber toe cap that defined hip-hop and street culture.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Core Black / White',
				colorHex: '#111111',
				colorFamily: 'black',
				price: 110,
				image: 2,
				cloudinaryId: 'adidas-superstar-core-black_x5n1uf',
				stock: stockFull(10),
			},
		],
	},
	{
		slug: 'adidas-stan-smith',
		name: 'Stan Smith',
		description:
			'Minimal tennis heritage. Clean white leather with perforated three stripes and a green heel tab — forever fresh.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Cloud White / Green',
				colorHex: '#16A34A',
				colorFamily: 'green',
				price: 100,
				image: 8,
				cloudinaryId: 'adidas-stan-smith-white-green_nwfkwj',
				stock: stockFull(10),
			},
		],
	},
	{
		slug: 'adidas-forum-low-mesa',
		name: 'Forum Low Mesa',
		description:
			'Basketball archive style. Premium leather with an adjustable ankle strap and classic three-stripes detailing.',
		brand: 'Adidas',
		category: 'basketball',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Brown',
				colorHex: '#8B5E3C',
				colorFamily: 'brown',
				price: 109,
				image: 7,
				cloudinaryId: 'adidas-forum-low-mesa-brown_dmnn3c',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'adidas-sl72',
		name: 'SL 72',
		description:
			'Retro runner with a slim silhouette. Nylon and suede upper on a lightweight outsole — 1970s track heritage.',
		brand: 'Adidas',
		category: 'running',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'Collegiate Green',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 100,
				image: 3,
				cloudinaryId: 'adidas-sl72-green_kykdip',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'adidas-ultraboost-light',
		name: 'Ultraboost Light',
		description:
			'The lightest Ultraboost yet. Responsive Light Boost, a supportive cage, and a Primeknit+ upper for daily miles.',
		brand: 'Adidas',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Core Black',
				colorHex: '#101010',
				colorFamily: 'black',
				price: 169,
				image: 12,
				cloudinaryId: 'adidas-ultraboost-light-core-black_iklug1',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'adidas-response-cl',
		name: 'Response CL',
		description:
			'Early-2000s trail runner reborn. Mesh and synthetic overlays with Adiprene cushioning in a chunky retro package.',
		brand: 'Adidas',
		category: 'running',
		gender: 'men',
		badge: 'discount',
		discountValue: 20,
		variants: [
			{
				color: 'Grey / Teal',
				colorHex: '#6B7078',
				colorFamily: 'grey',
				price: 119,
				image: 9,
				cloudinaryId: 'adidas-response-cl-grey_beivtj',
				stock: stockFull(8),
			},
		],
	},

	// --- New Balance (9) ----------------------------------------------------
	{
		slug: 'new-balance-550',
		name: '550',
		description:
			'Retro hoops heritage. A clean leather upper with perforated details and just the right amount of colour.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'new',
		variants: [
			{
				color: 'White / Green',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				description:
					'White leather 550 with green accents. Perforated details and clean court proportions.',
				price: 139,
				image: 8,
				cloudinaryId: 'new-balance-550-green_oa0rev',
				stock: stockFull(9),
			},
			{
				color: 'Sea Salt',
				colorHex: '#F5F0E8',
				colorFamily: 'cream',
				description:
					'Retro hoops 550 in soft sea-salt tones. Perforated leather and clean court proportions.',
				price: 139,
				image: 8,
				cloudinaryId: 'new-balance-550-sear-salt_q53pga',
				stock: stockFull(7),
			},
			{
				color: 'Court Purple',
				colorHex: '#6B21A8',
				colorFamily: 'purple',
				description:
					'White leather 550 with court-purple overlays. Retro hoops proportions with loud colour blocking.',
				price: 139,
				image: 19,
				cloudinaryId: 'new-balance-550-court-purple_fqqwuv',
				stock: stockFull(7),
			},
			{
				color: 'Sunny Yellow',
				colorHex: '#FACC15',
				colorFamily: 'yellow',
				description:
					'550 punched up with sunny yellow accents. Clean court silhouette, zero subtlety.',
				price: 139,
				image: 16,
				cloudinaryId: 'new-balance-550-sunny-yellow_sctul6',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'new-balance-574',
		name: '574',
		description:
			'The everyday icon. ENCAP midsole cushioning and a suede-mesh upper in timeless grey — built for daily wear.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 99,
				image: 9,
				cloudinaryId: 'new-balance-574-grey_oqrkzx',
				stock: stockFull(10),
			},
		],
	},
	{
		slug: 'new-balance-9060',
		name: '9060',
		description:
			'A bold evolution of the 99X lineage. Wavy overlays over chunky ABZORB and SBS cushioning for a Y2K look.',
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'discount',
		discountValue: 15,
		variants: [
			{
				color: 'Rain Cloud',
				colorHex: '#8A8D91',
				colorFamily: 'grey',
				price: 169,
				image: 9,
				cloudinaryId: 'new-balance-9060-shadow-grey_e8p76n',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'new-balance-2002r',
		name: "2002R 'Rain Cloud'",
		description:
			'Premium comfort in grey. Suede-and-mesh construction with N-ergy and ABZORB cushioning for all-day wear.',
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Rain Cloud',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 159,
				image: 9,
				cloudinaryId: 'new-balance-2002r-grey_mfgz4w',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'new-balance-990v6',
		name: '990v6',
		description:
			'Made in USA heritage. Premium pigskin suede and mesh with FuelCell cushioning — the pinnacle of NB craftsmanship.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 169,
				image: 11,
				cloudinaryId: 'new-balance-990v6-grey_z9alzv',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'new-balance-530',
		name: '530',
		description:
			'Y2K runner revival. Open mesh upper with ABZORB and N-ergy cushioning in a sleek, nostalgic silhouette.',
		brand: 'New Balance',
		category: 'running',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'White / Silver',
				colorHex: '#F5F5F5',
				colorFamily: 'white',
				price: 119,
				image: 10,
				cloudinaryId: 'new-balance-530-triple-white_ncn6pk',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'new-balance-327',
		name: '327',
		description:
			'Retro-inspired design with an oversized N logo. Suede and nylon upper on a wedge-like outsole for bold style.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'women',
		badge: null,
		variants: [
			{
				color: 'Moonbeam',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 119,
				image: 8,
				cloudinaryId: 'new-balance-327-moonbeam_tqtuvj',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'new-balance-fresh-foam-1080',
		name: 'Fresh Foam X 1080v12',
		description:
			'Plush daily trainer. Fresh Foam X midsole and a Hypoknit upper deliver cloud-like cushioning mile after mile.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Black / White',
				colorHex: '#111111',
				colorFamily: 'black',
				price: 159,
				image: 12,
				cloudinaryId: 'new-balance-fresh-foam-1080-black-white_yuzbdk',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'new-balance-480',
		name: '480',
		description:
			'Low-profile court heritage. A clean leather upper with vintage NB branding and a cupsole for everyday style.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'men',
		badge: 'discount',
		discountValue: 10,
		variants: [
			{
				color: 'White / Navy',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 109,
				image: 7,
				cloudinaryId: 'new-balance-480-white_xawegi',
				stock: stockFull(9),
			},
		],
	},

	// --- ASICS (7) ----------------------------------------------------------
	{
		slug: 'asics-gel-kayano-14',
		name: 'GEL-Kayano 14',
		description:
			'The archival stability runner. Layered overlays, dual-density GEL, and a distinctly metallic silver upper.',
		brand: 'ASICS',
		category: 'running',
		gender: 'men',
		badge: 'discount',
		discountValue: 25,
		variants: [
			{
				color: 'Silver / Black',
				colorHex: '#A9AEB4',
				colorFamily: 'silver',
				price: 169,
				image: 11,
				cloudinaryId: 'asics-gel-kayano-14-silver-black_dmclm9',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'asics-gel-1130',
		name: 'GEL-1130',
		description:
			'Early-2000s running DNA. A mesh-and-synthetic upper with rearfoot GEL in understated quiet-luxury tones.',
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'White / Clay Grey',
				colorHex: '#D9D2C7',
				colorFamily: 'white',
				price: 129,
				image: 10,
				cloudinaryId: 'asics-gel-1130-white-clay-gray_wtnxqu',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'asics-gel-nyc',
		name: 'GEL-NYC',
		description: 'A hybrid of two ASICS icons. Chunky, comfortable, and finished in a versatile graphite grey.',
		brand: 'ASICS',
		category: 'lifestyle',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'Graphite Grey',
				colorHex: '#6B7078',
				colorFamily: 'grey',
				price: 159,
				image: 9,
				cloudinaryId: 'asics-gel-nyc-graphite-gray_h84mmb',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'asics-gel-kahana',
		name: 'GEL-Kahana 8',
		description:
			'Trail-ready GEL cushioning. Rugged outsole and layered upper for outdoor adventures with retro runner style.',
		brand: 'ASICS',
		category: 'running',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Olive / Black',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 139,
				image: 3,
				cloudinaryId: 'asics-gel-kahana-green_cg2pb5',
				stock: stockFull(7),
			},
		],
	},
	{
		slug: 'asics-japan-s',
		name: 'Japan S',
		description:
			'Low-profile court classic. Smooth leather upper with a vulcanised sole — minimalist Japanese design heritage.',
		brand: 'ASICS',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'White / Peacoat',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				description:
					'White leather Japan S with peacoat accents. Clean lines and a vulcanised-inspired outsole.',
				price: 89,
				image: 8,
				cloudinaryId: 'asics-japan-s-white-peacote_zcpvdp',
				stock: stockFull(10),
			},
			{
				color: 'Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'cream',
				description:
					'Minimal court classic in cream leather. Clean lines and a vulcanized-inspired outsole.',
				price: 89,
				image: 8,
				cloudinaryId: 'asics-japan-s-wmns-white-cream_pikgz2',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'asics-gt-2160',
		name: 'GT-2160',
		description:
			'Stability runner archive. Open mesh with GEL technology and bold colour accents from the early 2000s era.',
		brand: 'ASICS',
		category: 'running',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'White / Pure Silver',
				colorHex: '#F5F5F5',
				colorFamily: 'white',
				price: 129,
				image: 10,
				cloudinaryId: 'asics-gt-2160-white-silver_gjw6fs',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'asics-gel-kahana-tr-v4',
		name: 'Excelsior',
		description:
			'Heritage track spike silhouette. Nylon upper with a slim profile and vintage ASICS branding for retro appeal.',
		brand: 'ASICS',
		category: 'lifestyle',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'White / Classic Red',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 99,
				image: 5,
				cloudinaryId: 'asics-gel-kahana-tr-v4-red_gatryb',
				stock: stockFull(9),
			},
		],
	},

	// --- Puma (6) -----------------------------------------------------------
	{
		slug: 'puma-speedcat-og',
		name: 'Speedcat OG',
		description:
			'Motorsport DNA in a low-profile sneaker. Suede upper with the iconic Formstrip and a sleek, race-ready silhouette.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'Red / White',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 100,
				image: 5,
				cloudinaryId: 'puma-speedcat-og-red_eylfo8',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'puma-palermo-og',
		name: 'Palermo OG',
		description:
			'A terrace icon revived. Soft suede, a T-toe overlay, and a gum sole — Palermo from pitch to pavement.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'new',
		variants: [
			{
				color: 'White / Green',
				colorHex: '#3E8E5A',
				colorFamily: 'green',
				description:
					'Soft suede Palermo with green accents, a T-toe overlay, and a gum sole in a fresh colourway.',
				price: 100,
				image: 3,
				cloudinaryId: 'puma-palermo-green_qqtgou',
				stock: stockFull(9),
			},
			{
				color: 'Vintage Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'cream',
				description:
					'Terrace Palermo in vintage-wash cream. T-toe overlay and gum sole with premium finishing.',
				price: 100,
				image: 8,
				cloudinaryId: 'puma-palermo-vintage-cream_ge9pdh',
				stock: stockFull(7),
			},
			{
				color: 'Hot Pink',
				colorHex: '#FF2D95',
				colorFamily: 'pink',
				description:
					'Palermo OG in hot pink suede. T-toe overlay and gum sole — terrace icon turned volume up.',
				price: 100,
				image: 18,
				cloudinaryId: 'puma-palermo-og-hot-pink_k6xsek',
				stock: stockFull(7),
			},
			{
				color: 'Lemon Yellow',
				colorHex: '#FDE047',
				colorFamily: 'yellow',
				description:
					'Sunny lemon Palermo with soft suede and a gum sole. Easy loud for everyday rotation.',
				price: 100,
				image: 16,
				cloudinaryId: 'puma-palermo-og-lemon-yellow_k9kf65',
				stock: stockFull(6),
			},
		],
	},
	{
		slug: 'puma-suede-classic',
		name: 'Suede Classic',
		description:
			'The original b-boy staple. Soft suede upper with a Formstrip and a rubber cupsole — hip-hop history on your feet.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Regal Red',
				colorHex: '#8B1A1A',
				colorFamily: 'red',
				price: 89,
				image: 5,
				cloudinaryId: 'puma-suede-classic-red_xv6shg',
				stock: stockFull(10),
			},
		],
	},
	{
		slug: 'puma-easy-rider',
		name: 'Easy Rider',
		description: '70s running heritage. Nylon and suede upper with a textured midsole and bold Formstrip branding.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Black / Yellow',
				colorHex: '#EAB308',
				colorFamily: 'yellow',
				price: 110,
				image: 2,
				cloudinaryId: 'puma-easy-rider-black_jjnsao',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'puma-mostro',
		name: 'Mostro',
		description: 'The spiky-soled cult classic returns. A minimal slip-on silhouette with a bold, aggressive outsole.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Black',
				colorHex: '#141414',
				colorFamily: 'black',
				price: 130,
				image: 2,
				cloudinaryId: 'puma-mostro-black_t7vdrk',
				stock: stockOos(),
			},
		],
	},
	{
		slug: 'puma-clyde',
		name: 'Clyde',
		description:
			'Named for Walt Frazier. Premium suede with a low-cut profile and gold Clyde branding — basketball royalty.',
		brand: 'Puma',
		category: 'basketball',
		gender: 'men',
		badge: null,
		variants: [
			{
				color: 'Navy / Gold',
				colorHex: '#C9A227',
				colorFamily: 'gold',
				price: 110,
				image: 1,
				cloudinaryId: 'puma-clyde-gold_etut95',
				stock: stockFull(8),
			},
		],
	},

	// --- Converse (4) -------------------------------------------------------
	{
		slug: 'converse-chuck-70-hi',
		name: 'Chuck 70 Hi',
		description:
			'The premium Chuck. Higher rubber foxing, cushioned Ortholite footbed, and vintage canvas construction.',
		brand: 'Converse',
		category: 'lifestyle',
		gender: 'women',
		badge: null,
		variants: [
			{
				color: 'Black',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				description:
					'Chuck 70 Hi in true black canvas. Higher foxing, Ortholite sockliner, and vintage finishing.',
				price: 89,
				image: 2,
				cloudinaryId: 'converse-chuck-70-hi-black_ge3vh8',
				stock: stockFull(10),
			},
			{
				color: 'Parchment',
				colorHex: '#F5F0E8',
				colorFamily: 'cream',
				description:
					'Premium Chuck 70 in parchment canvas. Higher foxing, Ortholite sockliner, and vintage finishing.',
				price: 89,
				image: 8,
				cloudinaryId: 'converse-chuck-70-hi-parchment_yhkbul',
				stock: stockFull(8),
			},
			{
				color: 'Navy',
				colorHex: '#1E2F4D',
				colorFamily: 'navy',
				description:
					'Chuck 70 Hi in deep navy canvas. Higher foxing, Ortholite sockliner, and vintage finishing.',
				price: 89,
				image: 1,
				cloudinaryId: 'converse-chuck-70-hi-navy_kdd44w',
				stock: stockFull(8),
			},
		],
	},
	{
		slug: 'converse-chuck-70-low',
		name: 'Chuck 70 Low',
		description: 'Low-cut premium canvas. Same upgraded construction as the Hi with a clean, versatile silhouette.',
		brand: 'Converse',
		category: 'lifestyle',
		gender: 'unisex',
		badge: null,
		variants: [
			{
				color: 'Parchment',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 89,
				image: 8,
				cloudinaryId: 'converse-chuck-70-low_drhq04',
				stock: stockFull(10),
			},
		],
	},
	{
		slug: 'converse-one-star-pro',
		name: 'One Star Pro',
		description: 'Skate-ready heritage. A durable suede upper, Lunarlon cushioning, and the signature single star.',
		brand: 'Converse',
		category: 'skateboarding',
		gender: 'men',
		badge: 'new',
		variants: [
			{
				color: 'Navy',
				colorHex: '#22304A',
				colorFamily: 'navy',
				price: 95,
				image: 1,
				cloudinaryId: 'converse-one-star-pro-blue_hwuq6l',
				stock: stockFull(9),
			},
		],
	},
	{
		slug: 'converse-run-star-hike',
		name: 'Run Star Hike Hi',
		description: 'A Chuck on a jagged, chunky platform. Bold proportions with the classic canvas high-top up top.',
		brand: 'Converse',
		category: 'lifestyle',
		gender: 'women',
		badge: 'discount',
		discountValue: 20,
		variants: [
			{
				color: 'White',
				colorHex: '#F2F2F2',
				colorFamily: 'white',
				price: 110,
				image: 8,
				cloudinaryId: 'onverse-run-star-hike-white_oa3rzb',
				stock: stockFull(8),
			},
		],
	},
];
