import { stockLimited, upcomingAt, UPCOMING_DROP, type SeedProduct } from './types';

// ---------------------------------------------------------------------------
// DROPS — 50 limited models (€170–420, sparse stock)
// Only store brands: Nike · Adidas · New Balance · ASICS · Puma · Converse
// Includes 6 upcoming products with availableAt
// ---------------------------------------------------------------------------

export const DROPS: SeedProduct[] = [
	// --- Upcoming drops (6) -------------------------------------------------
	{
		slug: 'nike-air-max-90-infrared',
		name: "Air Max 90 'Infrared' OG",
		description:
			'The colourway that defined Air Max. Infrared accents on a white mesh-and-leather upper — a collector essential.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: UPCOMING_DROP.dropsAt,
		heroImageUrl: '/dropAirMax.jpg',
		variants: [
			{
				color: 'Infrared',
				colorHex: '#E85D2A',
				colorFamily: 'orange',
				price: 169,
				image: 0,
				cloudinaryId: 'nike-air-max-90-infrared_ya3yrv',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-sb-dunk-low-tokyo-nights',
		name: "SB Dunk Low 'Tokyo Nights'",
		description: 'Neon-lit city energy. Premium suede and leather with glow accents inspired by Tokyo after dark.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('nike-sb-dunk-low-tokyo-nights'),
		variants: [
			{
				color: 'Tokyo Nights',
				colorHex: '#F5F0E8',
				colorFamily: 'Cream',
				price: 189,
				image: 3,
				cloudinaryId: 'nike-sb-dunk-low-tokyo-nights_ubdwwl',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-samba-wales-bonner-cream',
		name: "Samba Wales Bonner 'Cream'",
		description:
			'Grace Wales Bonner reimagines the Samba. Croc-embossed leather and cream tones with refined gold detailing.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('adidas-samba-wales-bonner-cream'),
		variants: [
			{
				color: 'Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 220,
				image: 8,
				cloudinaryId: 'adidas-samba-wales-bonner-cream-white_v4rrh8',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-speedcat-porsche',
		name: 'Speedcat x Porsche',
		description:
			'Motorsport DNA on the Speedcat. Low-profile racing suede with Porsche branding and a gum rubber outsole.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('puma-speedcat-porsche'),
		variants: [
			{
				color: 'Archive Green',
				colorHex: '#2E4A3E',
				colorFamily: 'green',
				price: 180,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-990v6-joe-freshgoods',
		name: '990v6 x Joe Freshgoods',
		description:
			"Joe Freshgoods' First in Flight energy on the 990v6. Soft pastels, premium pigskin, and Made-in-USA craft.",
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('new-balance-990v6-joe-freshgoods'),
		variants: [
			{
				color: 'First in Flight',
				colorHex: '#C4A882',
				colorFamily: 'brown',
				price: 260,
				image: 4,
				cloudinaryId: 'new-balance-990v6-joe-freshgoods-prom-blue_j2gngx',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-kayano-14-kith',
		name: 'GEL-Kayano 14 x Kith',
		description:
			"Kith's take on the Kayano 14. Layered metallic overlays with exclusive colour blocking and co-branding.",
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('asics-gel-kayano-14-kith'),
		variants: [
			{
				color: 'Kith Cream',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 210,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},

	// --- Available now — promo popup product --------------------------------
	{
		slug: 'nike-sb-dunk-low-limited-colorways',
		name: 'SB Dunk Low — Limited Colorways',
		description:
			'Three exclusive SB Dunk colourways drop in limited quantities. Zoom Air insole and padded tongue for the board.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Court Purple',
				colorHex: '#7B6B9B',
				colorFamily: 'purple',
				price: 189,
				image: 5,
				cloudinaryId: 'nike-sb-dunk-low-court-purple_gbflz7',
				stock: stockLimited(),
			},
			{
				color: 'Green Gum',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 199,
				image: 3,
				cloudinaryId: 'nike-sb-dunk-low-classic-green_y8lzgl',
				stock: stockLimited(),
			},
			{
				color: 'Black Gum',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 209,
				image: 2,
				cloudinaryId: 'nike-sb-dunk-low-black-gum_krslpy',
				stock: stockLimited(),
			},
		],
	},

	// --- Limited editions (43) — store brands only --------------------------
	// Nike
	{
		slug: 'air-jordan-1-lost-and-found',
		name: "Air Jordan 1 'Lost & Found'",
		description:
			'Aged Chicago colour blocking with cracked leather and a vintage feel. A modern twist on the most iconic Jordan.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Chicago Reimagined',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 190,
				image: 5,
				cloudinaryId: 'air-jordan-1-lost-and-found-red_qxotsi',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'air-jordan-4-black-cat',
		name: "Air Jordan 4 Retro 'Black Cat'",
		description:
			'All-black stealth Jordan 4. Mesh panels, visible Air, and the cat-eye lace loops in a monochrome finish.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Black Cat',
				colorHex: '#141414',
				colorFamily: 'black',
				price: 220,
				image: 2,
				cloudinaryId: 'air-jordan-4-black-cat_xfpa79',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'air-jordan-1-chicago',
		name: "Air Jordan 1 Retro High OG 'Chicago'",
		description:
			'The original colourway. Red, white, and black leather with Nike Air branding — the pair that started it all.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Chicago',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 189,
				image: 5,
				cloudinaryId: 'air-jordan-1-chicago-red_amgjtx',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-dunk-low-university-blue',
		name: "Dunk Low 'University Blue'",
		description: 'UNC-inspired blue suede overlays on white leather. A clean campus Dunk with everyday versatility.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'University Blue',
				colorHex: '#7BA3C9',
				colorFamily: 'blue',
				price: 175,
				image: 1,
				cloudinaryId: 'nike-dunk-low-university-blue_i0mmva',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-dunk-high-black',
		name: "Dunk High 'Black White'",
		description: 'High-top Dunk in stark black. Padded collar and classic cupsole for skate and street.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Black',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 170,
				image: 2,
				cloudinaryId: 'nike-air-force-1-low-black_g7uu0o',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-air-force-1-low-black',
		name: "Air Force 1 '07 'Triple Black'",
		description: 'All-black AF1 with tonal Swoosh. Premium leather and the pivot-point outsole in stealth mode.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Triple Black',
				colorHex: '#111111',
				colorFamily: 'black',
				price: 175,
				image: 2,
				cloudinaryId: 'nike-air-force-1-low-black_g7uu0o',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-air-max-90-bacon',
		name: "Air Max 90 'Bacon'",
		description: 'Pink, red, and white layered like the fan-favourite Bacon pack. Visible Air and waffle outsole.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Bacon',
				colorHex: '#E8B4B8',
				colorFamily: 'pink',
				price: 185,
				image: 5,
				cloudinaryId: 'nike-air-max-90-bacon_koxgdq',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-air-max-1-patta',
		name: "Air Max 1 'Patta Waves'",
		description: 'Wave-pattern overlays and premium suede on the Air Max 1. A limited colour story with street DNA.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Waves Brown',
				colorHex: '#8B5E3C',
				colorFamily: 'brown',
				price: 195,
				image: 9,
				cloudinaryId: 'nike-air-max-1-patta-monarch_usvxhf',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-blazer-mid-77-vintage',
		name: "Blazer Mid '77 Vintage",
		description: 'Aged midsole and classic Blazer proportions. Vintage treatment on a basketball original.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Sail / Gum',
				colorHex: '#FFFFFF',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'nike-blazer-mid-77-vintage_vyiu1a',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-sb-dunk-low-pro-iso',
		name: 'SB Dunk Low Pro ISO',
		description: 'Skate-focused Dunk with ISO tooling and Zoom Air. Sticky rubber and a durable suede upper.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Orange Label',
				colorHex: '#FFFFFF',
				colorFamily: 'white',
				price: 180,
				image: 0,
				cloudinaryId: 'nike-sb-dunk-low-pro-iso_cpn5nl',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-sb-dunk-high-soft-grey',
		name: "SB Dunk High 'Beige'",
		description:
			'Premium beige suede on a SB Dunk High. Clean, understated, and built for the board with Zoom Air.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Beige',
				colorHex: '#D4C4A8',
				colorFamily: 'beige',
				price: 170,
				image: 9,
				cloudinaryId: 'nike-sb-dunk-high-soft-grey_snqw1l',
				stock: stockLimited(),
			},
		],
	},

	// Adidas
	{
		slug: 'adidas-samba-og-collegiate-green',
		name: "Samba OG 'Collegiate Green'",
		description: 'Terrace classic in deep green suede. Gum sole, T-toe overlay, and gold foil Samba branding.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Collegiate Green',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 175,
				image: 3,
				cloudinaryId: 'adidas-samba-og-collegiate-green_wl6c36',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-handball-spezial-shadow-red',
		name: "Handball Spezial 'Shadow Red'",
		description: 'Soft suede Spezial in a deep red tone. Gum outsole and three stripes for indoor-to-street style.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Shadow Red',
				colorHex: '#8B1A1A',
				colorFamily: 'red',
				price: 170,
				image: 5,
				cloudinaryId: 'adidas-handball-spezial-shadow-red_jvjjpd',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-gazelle-indoor-blue-bird',
		name: "Gazelle Indoor 'Blue Bird'",
		description: 'Retro indoor Gazelle with plush blue suede and contrast stripes on a low gum outsole.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Blue Bird',
				colorHex: '#3B6FB5',
				colorFamily: 'blue',
				price: 170,
				image: 1,
				cloudinaryId: 'adidas-gazelle-indoor-blue-bird_dvp1xg',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-campus-00s-core-black',
		name: "Campus 00s 'Core Black'",
		description: 'Chunky 2000s Campus in premium black suede. Oversized tongue and bold three-stripe branding.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Core Black',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 175,
				image: 4,
				cloudinaryId: 'adidas-campus-00s-core-black_plq0rr',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-samba-og-night-indigo',
		name: "Samba OG 'Night Indigo'",
		description: 'Deep indigo suede Samba with gum sole. A darker take on the terrace icon for limited drop energy.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Night Indigo',
				colorHex: '#D4C4A8',
				colorFamily: 'beige',
				price: 175,
				image: 1,
				cloudinaryId: 'adidas-samba-og-night-indigo_vw9knk',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-sl72-og-green',
		name: "SL 72 OG 'Green'",
		description: 'Vintage running silhouette revived. Nylon and suede upper in archival green with a molded midsole.',
		brand: 'Adidas',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Focus Olive',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 180,
				image: 3,
				cloudinaryId: 'adidas-sl72-og-green_pfpo4g',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-forum-low-cl',
		name: 'Forum Low CL',
		description: 'Basketball heritage in a low cut. Soft leather, ankle strap detail, and classic Forum proportions.',
		brand: 'Adidas',
		category: 'basketball',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Cloud White',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'adidas-forum-low-cl-shadow-red_qolqjy',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-response-cl-metal',
		name: "Response CL 'Metallic'",
		description: 'Early-2000s runner with metallic overlays. Responsive cushioning and a techy mesh upper.',
		brand: 'Adidas',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Silver Metallic',
				colorHex: '#C4C8CE',
				colorFamily: 'grey',
				price: 185,
				image: 11,
				cloudinaryId: 'adidas-response-cl-metal-grey_dae3wz',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-tokyo-pack-samba',
		name: "Samba OG 'Tokyo Pack'",
		description: 'City pack Samba with subtle Tokyo-inspired detailing. Soft leather and the classic gum outsole.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Tokyo Night',
				colorHex: '#6366F1',
				colorFamily: 'multi',
				price: 180,
				image: 2,
				cloudinaryId: 'adidas-tokyo-pack-samba-leopard_waaabh',
				stock: stockLimited(),
			},
		],
	},

	// New Balance
	{
		slug: 'new-balance-990v6-miusa-grey',
		name: "990v6 Made in USA 'Grey'",
		description:
			'Flagship Made-in-USA 990v6. Premium pigskin suede with FuelCell cushioning — the grey that started it all.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 210,
				image: 11,
				cloudinaryId: 'new-balance-990v6-miusa-grey_jvj3uj',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-992-miusa',
		name: '992 Made in USA',
		description: 'Archival Made-in-USA 992. ABZORB cushioning and a layered grey upper built for all-day comfort.',
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 230,
				image: 11,
				cloudinaryId: 'new-balance-992-miusa-grey_sbumnb',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-2002r-protection-pack',
		name: '2002R Protection Pack',
		description:
			'Rain-ready 2002R with muted overlays and technical mesh. A cult favourite from the Protection Pack series.',
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Rain Cloud',
				colorHex: '#8A8D91',
				colorFamily: 'grey',
				price: 190,
				image: 9,
				cloudinaryId: 'new-balance-2002r-protection-pack-rain-cloud_kztfzg',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-1906r-metallic',
		name: "1906R 'Silver Metallic'",
		description: 'Futuristic early-2000s tech runner. Stability web, N-ergy heel, and a metallic silver finish.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Silver Metallic',
				colorHex: '#C4C8CE',
				colorFamily: 'grey',
				price: 185,
				image: 11,
				cloudinaryId: 'new-balance-1906r-metallic-cream_xsiuei',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-550-sea-salt',
		name: "550 'Sea Salt'",
		description: 'Retro hoops 550 in soft sea-salt tones. Perforated leather and clean court proportions.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Sea Salt',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 175,
				image: 8,
				cloudinaryId: 'new-balance-550-sea-salt_nmnbrc',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-9060-mushroom',
		name: "9060 'Mushroom'",
		description: 'Bold Y2K-inspired 9060 in mushroom tones. Wavy overlays over ABZORB and SBS cushioning.',
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Mushroom',
				colorHex: '#C4A882',
				colorFamily: 'brown',
				price: 180,
				image: 4,
				cloudinaryId: 'new-balance-9060-mushroom_t0jcca',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-990v4-miusa',
		name: '990v4 Made in USA',
		description: 'Heritage Made-in-USA 990v4. Dual-density midsole and a premium grey pigskin upper.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 200,
				image: 11,
				cloudinaryId: 'new-balance-990v4-miusa-grey_xmexjf',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-574-legacy',
		name: "574 Legacy 'Military Green'",
		description: 'Updated 574 with legacy tooling. Military green suede and ENCAP cushioning for everyday wear.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Dark Green',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 170,
				image: 3,
				cloudinaryId: 'new-balance-574-legacy-dark-green_igkis7',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-327-moonbeam',
		name: "327 'Moonbeam'",
		description: 'Oversized N branding on a lightweight 327. Moonbeam tones with a scalloped midsole.',
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Moonbeam Outer Space',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'new-balance-327-moonbeam-outer-space_nydfj7',
				stock: stockLimited(),
			},
		],
	},

	// ASICS
	{
		slug: 'asics-gel-kayano-14-cream-black',
		name: "GEL-Kayano 14 'Cream Black'",
		description: 'Archival stability runner. Cream and black layered overlays with dual-density GEL cushioning.',
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Cream / Black',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 190,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-1130-clay',
		name: "GEL-1130 'Clay Grey'",
		description: 'Early-2000s running DNA. Mesh-and-synthetic upper with rearfoot GEL in quiet clay tones.',
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Clay Grey',
				colorHex: '#D9D2C7',
				colorFamily: 'grey',
				price: 175,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-nyc-graphite',
		name: "GEL-NYC 'Graphite'",
		description: 'Hybrid of two ASICS icons. Chunky, comfortable, and finished in versatile graphite grey.',
		brand: 'ASICS',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Graphite Grey',
				colorHex: '#6B7078',
				colorFamily: 'grey',
				price: 180,
				image: 9,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-kahana-8-olive',
		name: "GEL-Kahana 8 'Olive'",
		description: 'Trail-inspired Kahana in olive tones. GEL cushioning and a grippy outsole for city and path.',
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Olive / Black',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 175,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gt-2160-pure-silver',
		name: "GT-2160 'Pure Silver'",
		description: 'Metallic silver GT-2160 with stability heritage. Lightweight upper and classic ASICS tooling.',
		brand: 'ASICS',
		category: 'running',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Pure Silver',
				colorHex: '#C4C8CE',
				colorFamily: 'grey',
				price: 170,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-japan-s-cream',
		name: "Japan S 'Cream'",
		description: 'Minimal court classic in cream leather. Clean lines and a vulcanized-inspired outsole.',
		brand: 'ASICS',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-quantum-360',
		name: "GEL-Quantum 360 'Black Neon'",
		description: 'Full-length GEL midsole with neon accents. Tech runner energy in a limited black colourway.',
		brand: 'ASICS',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Black / Neon',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 195,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},

	// Puma
	{
		slug: 'puma-speedcat-og-red',
		name: "Speedcat OG 'Red'",
		description: 'Racing flat in bold red suede. Low profile, gum sole, and motorsport heritage for a limited drop.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'High Risk Red',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 175,
				image: 5,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-palermo-leather',
		name: "Palermo Leather 'Vintage'",
		description: 'Terrace Palermo in vintage-wash leather. T-toe overlay and gum sole with premium finishing.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Vintage Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-mostro-echo',
		name: 'Mostro Echo',
		description: 'The spiky-soled cult classic returns in Echo colourways. Minimal slip-on with an aggressive outsole.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Echo Black',
				colorHex: '#141414',
				colorFamily: 'black',
				price: 180,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-suede-xl-olive',
		name: "Suede XL 'Olive'",
		description: 'Supersized Suede with a chunky sole. Olive suede upper for an exaggerated retro stance.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Olive',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 170,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-clyde-court',
		name: 'Clyde Court Disrupt',
		description: 'Basketball Clyde updated for the court. Premium leather and disruptive tooling in a limited pack.',
		brand: 'Puma',
		category: 'basketball',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Navy / Gold',
				colorHex: '#1E3A5F',
				colorFamily: 'blue',
				price: 175,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},

	// Converse
	{
		slug: 'converse-chuck-70-hi-parchment',
		name: "Chuck 70 Hi 'Parchment'",
		description: 'Premium Chuck 70 in parchment canvas. Higher foxing, Ortholite sockliner, and vintage finishing.',
		brand: 'Converse',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Parchment',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 170,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'converse-one-star-pro-ox',
		name: "One Star Pro OX 'Navy'",
		description: 'Skate-ready One Star in navy suede. Lunarlon cushioning and the signature single star.',
		brand: 'Converse',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Navy',
				colorHex: '#22304A',
				colorFamily: 'blue',
				price: 170,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
];
