import {
  stockLimited,
  upcomingAt,
  UPCOMING_DROP,
  type SeedProduct,
} from "./types";

// ---------------------------------------------------------------------------
// DROPS — 50 limited / collab models (€170–420, sparse stock)
// Includes 6 upcoming products with availableAt
// ---------------------------------------------------------------------------

export const DROPS: SeedProduct[] = [
	// --- Upcoming drops (6) -------------------------------------------------
	{
		slug: 'nike-air-max-90-infrared',
		name: "Air Max 90 'Infrared' OG",
		description:
			'The colourway that defined Air Max. Infrared accents on a white mesh-and-leather upper — a collector essential.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: UPCOMING_DROP.dropsAt,
		heroImageUrl: '/dropAirMax.jpg',
		variants: [
			{
				color: 'Infrared',
				colorHex: '#E85D2A',
				colorFamily: 'orange',
				price: 169,
				image: 0,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-sb-dunk-low-tokyo-nights',
		name: "SB Dunk Low 'Tokyo Nights'",
		description: 'Neon-lit city energy. Premium suede and leather with glow accents inspired by Tokyo after dark.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('nike-sb-dunk-low-tokyo-nights'),
		variants: [
			{
				color: 'Tokyo Nights',
				colorHex: '#1A1A2E',
				colorFamily: 'black',
				price: 189,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-samba-wales-bonner-cream',
		name: "Samba Wales Bonner 'Cream'",
		description:
			'Grace Wales Bonner reimagines the Samba. Croc-embossed leather and cream tones with refined gold detailing.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('adidas-samba-wales-bonner-cream'),
		variants: [
			{
				color: 'Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 220,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'puma-palermo-ami-paris',
		name: 'Palermo x Ami Paris',
		description:
			'Ami Paris brings Parisian elegance to the Palermo. Soft suede with a heart logo and tonal cream palette.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('puma-palermo-ami-paris'),
		variants: [
			{
				color: 'Ami Cream',
				colorHex: '#F5F0E8',
				colorFamily: 'white',
				price: 180,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-990v6-jjjjound',
		name: '990v6 x JJJJound',
		description:
			"JJJJound's minimalist eye on the 990v6. Premium grey tones and understated branding on Made-in-USA construction.",
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('new-balance-990v6-jjjjound'),
		variants: [
			{
				color: 'Mushroom',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 260,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-gel-kayano-14-kith',
		name: 'GEL-Kayano 14 x Kith',
		description:
			"Kith's take on the Kayano 14. Layered metallic overlays with exclusive colour blocking and co-branding.",
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		availableAt: upcomingAt('asics-gel-kayano-14-kith'),
		variants: [
			{
				color: 'Kith Cream',
				colorHex: '#E8E4DC',
				colorFamily: 'white',
				price: 210,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},

	// --- Available now — promo popup product --------------------------------
	{
		slug: 'nike-sb-dunk-low-limited-colorways',
		name: 'SB Dunk Low — Limited Colorways',
		description:
			'Three exclusive SB Dunk colourways drop in limited quantities. Zoom Air insole and padded tongue for the board.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'unisex',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Court Purple',
				colorHex: '#7B6B9B',
				colorFamily: 'purple',
				price: 189,
				image: 5,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
			{
				color: 'Green Gum',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 199,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
			{
				color: 'Black / Cream',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 209,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},

	// --- Collabs & grails (43) ----------------------------------------------
	{
		slug: 'travis-scott-jordan-1-low',
		name: 'Travis Scott x Air Jordan 1 Low',
		description:
			'Reverse Swoosh and hidden stash pocket. Cactus Jack branding on premium suede — one of the most sought-after collabs.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Mocha',
				colorHex: '#6B5344',
				colorFamily: 'brown',
				price: 420,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'jumpman-jack-tr',
		name: 'Jumpman Jack TR',
		description:
			"Travis Scott's signature silhouette. Bold strap details and earthy tones on a brand-new Jordan model.",
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Dark Mocha',
				colorHex: '#4A3728',
				colorFamily: 'brown',
				price: 210,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'off-white-dunk-low-lot',
		name: "Off-White x Dunk Low 'Lot'",
		description:
			"Virgil Abloh's deconstructed Dunk. Text overlays, zip tie, and exposed foam tongue in a numbered lot release.",
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Lot 1',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 380,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'off-white-air-force-1-mca',
		name: 'Off-White x Air Force 1 MCA',
		description:
			"Musée d'Art Contemporain exclusive. All-white AF1 with Off-White text and a silver Swoosh — gallery-grade grail.",
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'MCA White',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 350,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'off-white-blazer-low',
		name: 'Off-White x Blazer Low',
		description:
			"Deconstructed Blazer with Virgil's signature text and exposed tongue. A low-cut take on a Nike classic.",
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'White / University Red',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 290,
				image: 5,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-stussy-spiridon-caged-2',
		name: 'Stussy x Air Spiridon Cage 2',
		description:
			'Stussy brings fossil-stone tones to the Spiridon Cage 2. Mesh cage and bold co-branding for a cult favourite.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Fossil',
				colorHex: '#D9D2C7',
				colorFamily: 'grey',
				price: 190,
				image: 9,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-stussy-air-force-1',
		name: 'Stussy x Air Force 1',
		description:
			"Stussy's spin on the AF1. Premium materials with dual branding — a streetwear staple in limited release.",
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Triple White',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 180,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nocta-hot-step-2',
		name: 'NOCTA Hot Step 2',
		description:
			"Drake's NOCTA line delivers a futuristic runner. Bold proportions with reflective details and premium cushioning.",
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Black / Gold',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 210,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nocta-glide',
		name: 'NOCTA Glide',
		description:
			'A sleek NOCTA lifestyle slider-sneaker hybrid. Minimal upper with full-length cushioning for off-duty comfort.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Chrome',
				colorHex: '#B8BCC2',
				colorFamily: 'grey',
				price: 190,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'fragment-dunk-low',
		name: 'Fragment x Dunk Low',
		description:
			"Hiroshi Fujiwara's lightning bolt on the Dunk Low. Premium leather with a royal blue and white colour block.",
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Royal Blue',
				colorHex: '#1D3C8E',
				colorFamily: 'blue',
				price: 320,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'air-jordan-1-lost-and-found',
		name: "Air Jordan 1 'Lost & Found'",
		description:
			'Aged Chicago colourway with vintage packaging details. Cracked leather and yellowed soles tell a thrift-store story.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Chicago Reimagined',
				colorHex: '#C8102E',
				colorFamily: 'red',
				price: 190,
				image: 5,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'air-jordan-4-black-cat',
		name: "Air Jordan 4 Retro 'Black Cat'",
		description:
			'All-black nubuck upper with matching midsole. Stealthy, sleek, and one of the most coveted Jordan 4 colourways.',
		brand: 'Nike',
		category: 'basketball',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Black Cat',
				colorHex: '#141414',
				colorFamily: 'black',
				price: 220,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'wales-bonner-sl72',
		name: 'Wales Bonner x SL 72',
		description:
			"Grace Wales Bonner's refined take on the SL 72. Croc textures and warm tones celebrate Afro-Atlantic style.",
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Brown / Cream',
				colorHex: '#6B5344',
				colorFamily: 'brown',
				price: 200,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'pharrell-humanrace-samba',
		name: 'Pharrell x Humanrace Samba',
		description:
			"Pharrell's Humanrace lens on the Samba. Bold colour and sustainable materials with a message of unity.",
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Focus Olive',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 180,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'pharrell-nmd-hu',
		name: 'Pharrell x NMD Human Race',
		description: 'Human Race lettering on a Boost midsole. A bold statement sneaker that bridges culture and comfort.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Yellow',
				colorHex: '#F5C518',
				colorFamily: 'yellow',
				price: 250,
				image: 6,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'adidas-gucci-gazelle',
		name: 'Gucci x Gazelle',
		description: 'Gucci meets Gazelle. Premium suede with Interlocking G branding — luxury streetwear at its finest.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Green / Red',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 380,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'bad-bunny-campus',
		name: 'Bad Bunny x Campus',
		description:
			"Benito's take on the Campus. Bold colour blocking and premium suede with Latin flair and global appeal.",
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Wild Moss',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 190,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'bad-bunny-response-cl',
		name: 'Bad Bunny x Response CL',
		description:
			'Bad Bunny revives the Response CL. Chunky trail-runner aesthetic with vibrant colour and co-branding.',
		brand: 'Adidas',
		category: 'running',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Cloud White / Yellow',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 180,
				image: 9,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'kith-samba',
		name: 'Kith x Samba',
		description:
			"Kith's refined Samba collaboration. Premium materials and exclusive colourways for the Kith community.",
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Kith Classics',
				colorHex: '#111111',
				colorFamily: 'black',
				price: 170,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'yeezy-boost-350-v2-zebra',
		name: "Yeezy Boost 350 V2 'Zebra'",
		description:
			'Instantly recognisable. Full-length Boost under a breathable Primeknit upper with the signature striped pattern.',
		brand: 'Adidas',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		featured: true,
		variants: [
			{
				color: 'Zebra',
				colorHex: '#EDEDED',
				colorFamily: 'white',
				price: 249,
				image: 6,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'fenty-creeper',
		name: 'Fenty x Creeper',
		description:
			"Rihanna's punk-inspired Creeper. A platform sole and bold suede upper that redefined Puma collaborations.",
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Black Gum',
				colorHex: '#1A1A1A',
				colorFamily: 'black',
				price: 170,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'fenty-avanti',
		name: 'Fenty x Avanti',
		description:
			'Racing-inspired Avanti with Fenty flair. Sleek lines and a bold colour palette from the Fenty x Puma line.',
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Lavender',
				colorHex: '#7B6B9B',
				colorFamily: 'purple',
				price: 175,
				image: 5,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asap-rocky-mostro',
		name: 'A$AP Rocky x Mostro',
		description:
			"Rocky's spiky Mostro return. A minimal slip-on with an aggressive outsole — fashion-forward and fearless.",
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Black / Silver',
				colorHex: '#141414',
				colorFamily: 'black',
				price: 180,
				image: 2,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asap-rocky-inhale',
		name: 'A$AP Rocky x Inhale',
		description:
			"Futuristic Inhale silhouette with A$AP Rocky's design language. Translucent panels and bold proportions.",
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Grey / Orange',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 190,
				image: 9,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'jjjjound-palermo',
		name: 'JJJJound x Palermo',
		description:
			"JJJJound's quiet palette on the Palermo. Muted tones and premium suede for understated collab excellence.",
		brand: 'Puma',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Olive',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 170,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'butter-goods-slipstream',
		name: 'Butter Goods x Slipstream',
		description:
			'Australian skate label Butter Goods meets the Slipstream. Retro basketball style with skate-ready details.',
		brand: 'Puma',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Butter Navy',
				colorHex: '#1E3A5F',
				colorFamily: 'blue',
				price: 170,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'jjjjound-990v4',
		name: 'JJJJound x 990v4',
		description: "JJJJound's signature grey on the 990v4. Made-in-USA construction with minimalist co-branding.",
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 250,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'ald-550',
		name: 'Aimé Leon Dore x 550',
		description: "ALD's preppy take on the 550. Premium leather and exclusive colour blocking from the New York label.",
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Green / Yellow',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 210,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'ald-1906r',
		name: 'Aimé Leon Dore x 1906R',
		description:
			"ALD reimagines the 1906R. Metallic overlays and refined tones from one of streetwear's most respected labels.",
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Silver / Green',
				colorHex: '#C4C8CE',
				colorFamily: 'grey',
				price: 220,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'salehe-bembury-2002r',
		name: 'Salehe Bembury x 2002R',
		description:
			"Salehe Bembury's nature-inspired 2002R. Organic colour palettes and textured materials from the design polymath.",
		brand: 'New Balance',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Water Be the Guide',
				colorHex: '#3B6FB5',
				colorFamily: 'blue',
				price: 210,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'salehe-bembury-yurt-574',
		name: 'Salehe Bembury x YURT 574',
		description:
			"The YURT 574 transforms the classic runner. Salehe's outdoor-inspired design with rugged, earthy tones.",
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Tan / Orange',
				colorHex: '#C4A882',
				colorFamily: 'brown',
				price: 190,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'stone-island-574',
		name: 'Stone Island x 574',
		description:
			"Stone Island's compass badge meets the 574. Technical materials and military-inspired colour on a NB icon.",
		brand: 'New Balance',
		category: 'lifestyle',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Military Green',
				colorHex: '#4A5D23',
				colorFamily: 'green',
				price: 230,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-990v6-miusa-grey',
		name: "990v6 Made in USA 'Grey'",
		description:
			'Flagship Made-in-USA 990v6. Premium pigskin suede with FuelCell cushioning — the grey that started it all.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 210,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'new-balance-992-miusa',
		name: '992 Made in USA',
		description: 'The Steve Jobs favourite. ABZORB and C-CAP cushioning in a premium Made-in-USA grey colourway.',
		brand: 'New Balance',
		category: 'running',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Grey',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 230,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'kith-gel-1130',
		name: 'Kith x GEL-1130',
		description:
			"Kith's exclusive GEL-1130. Early-2000s runner aesthetic with premium materials and co-branded details.",
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Kith White',
				colorHex: '#FAFAFA',
				colorFamily: 'white',
				price: 190,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'jjjjound-gel-kayano-14',
		name: 'JJJJound x GEL-Kayano 14',
		description: "JJJJound's muted palette on the Kayano 14. Understated grey tones with premium layered construction.",
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Mushroom',
				colorHex: '#9CA3AF',
				colorFamily: 'grey',
				price: 210,
				image: 11,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'awake-ny-gel-kayano',
		name: 'Awake NY x GEL-Kayano 14',
		description:
			'Awake NY brings New York energy to the Kayano 14. Bold colour blocking and co-branding from the downtown label.',
		brand: 'ASICS',
		category: 'running',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Awake Blue',
				colorHex: '#1D3C8E',
				colorFamily: 'blue',
				price: 200,
				image: 1,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'cecilie-bahnsen-gel-terrain',
		name: 'Cecilie Bahnsen x GEL-Terrain',
		description:
			'Danish designer Cecilie Bahnsen reimagines the GEL-Terrain. Feminine details on a rugged outdoor silhouette.',
		brand: 'ASICS',
		category: 'running',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Pink / White',
				colorHex: '#E8B4B8',
				colorFamily: 'pink',
				price: 200,
				image: 8,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'asics-above-the-clouds-kayano',
		name: 'Above the Clouds x GEL-Kayano 14',
		description: "Melbourne's Above the Clouds puts an Antipodean spin on the Kayano 14. Exclusive regional colourway.",
		brand: 'ASICS',
		category: 'running',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Cloud Grey',
				colorHex: '#D1D5DB',
				colorFamily: 'grey',
				price: 190,
				image: 10,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'concepts-sb-dunk-low-orange-lobster',
		name: "Concepts x SB Dunk Low 'Orange Lobster'",
		description:
			"Concepts' lobster series returns in orange. Premium materials and aquatic-inspired details on the SB Dunk.",
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'men',
		badge: 'limited',
		variants: [
			{
				color: 'Orange Lobster',
				colorHex: '#E85D2A',
				colorFamily: 'orange',
				price: 320,
				image: 0,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'grateful-dead-sb-dunk',
		name: 'Grateful Dead x SB Dunk Low',
		description:
			'A dancing-bear celebration on the SB Dunk. Vibrant fur overlays and Deadhead details for a trippy classic.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Green Bear',
				colorHex: '#2E7D46',
				colorFamily: 'green',
				price: 350,
				image: 3,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-sb-dunk-high-soft-grey',
		name: "SB Dunk High 'Soft Grey'",
		description:
			'Premium soft grey suede on a SB Dunk High. Clean, understated, and built for the board with Zoom Air.',
		brand: 'Nike',
		category: 'skateboarding',
		gender: 'women',
		badge: 'limited',
		variants: [
			{
				color: 'Soft Grey',
				colorHex: '#D1D5DB',
				colorFamily: 'grey',
				price: 170,
				image: 9,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
	{
		slug: 'nike-stussy-cd-duck-sp',
		name: 'Stussy x CD Duck SP',
		description:
			'Stussy digs into the Nike archive. The CD Duck SP gets a surf-meets-street makeover with co-branding.',
		brand: 'Nike',
		category: 'lifestyle',
		gender: 'unisex',
		badge: 'limited',
		variants: [
			{
				color: 'Desert Ochre',
				colorHex: '#C4A882',
				colorFamily: 'brown',
				price: 180,
				image: 4,
				cloudinaryId: 'nike-dunk-low-panda_lalm69',
				stock: stockLimited(),
			},
		],
	},
];
